# Generated by Django 2.2.1 on 2019-05-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el lenguaje correspondiente (principal)', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='genero',
            field=models.ManyToManyField(help_text='Seleccione el género de la película', to='catalogo.Genero'),
        ),
        migrations.AddField(
            model_name='film',
            name='lengua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Language'),
        ),
    ]
