# Generated by Django 2.2.1 on 2019-05-21 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20190521_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='pais',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
