# Generated by Django 2.2.1 on 2019-05-22 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_film_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Directores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Usuarios'),
            preserve_default=False,
        ),
    ]
