# Generated by Django 2.2.1 on 2019-05-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20190522_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(upload_to='ImgDirectores'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(upload_to='ImgUsuarios'),
        ),
    ]
