# Generated by Django 2.2.1 on 2019-05-22 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20190522_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='cartel_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ImgFilm'),
            preserve_default=False,
        ),
    ]
