# Generated by Django 2.2.1 on 2019-05-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_filminstance_prestamo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filminstance',
            options={'ordering': ['prestado_a']},
        ),
        migrations.RenameField(
            model_name='filminstance',
            old_name='prestamo',
            new_name='prestado_a',
        ),
        migrations.RemoveField(
            model_name='filminstance',
            name='usuario',
        ),
    ]
